services:
  # Clickhouse
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    hostname: clickhouse
    network_mode: "host"
    environment:
      - CLICKHOUSE_DB=${AKAI_CH_DB:-bitswap_sniffer_db}
      - CLICKHOUSE_USER=${AKAI_CH_USER:-username}
      - CLICKHOUSE_PASSWORD=${AKAI_CH_PASSWORD:-password}
    ports:
      - "127.0.0.1:${CH_HTTP_PORT:-8123}:8123"
      - "127.0.0.1:${CH_NATIVE_PORT:-9000}:9000"
      - "127.0.0.1:${CH_SQL_PORT:-9005}:9005"
    healthcheck: # executed inside the container
      test: wget --no-verbose --tries=1 --spider http://localhost:8123/ping
      interval: 5s

  # Prometheus for real-time metrics
  prometheus:
    image: prom/prometheus:latest
    network_mode: "host"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.listen-address=${PROMETHEUS_ADDRESS:-localhost:9090}"
      - "--storage.tsdb.retention.time=1y"
      - "--web.enable-remote-write-receiver"
    ports:
      - "9090:9090"
